"""Theme taxonomy + derivation for Thematic Browsing (Feature B).

A theme is a named predicate over the controlled-vocab facets every saint
already carries. `match` is a list of RULES; a saint gets the theme if ANY rule
matches (OR). Within a rule, ALL field conditions must hold (AND); a field
condition holds if the saint's value(s) for that field intersect the listed
values. `match: []` = override-only (filled solely via the optional `Themes`
CSV column; renders only once it has saints).
"""

THEME_GROUPS = [
    "Life Circumstances", "Vocations", "Virtues", "Struggles & Trials",
    "Historical Themes", "Family & Relationships", "Miracles & Wonders",
    "Geographic Themes",
]

THEMES = [
    {"slug": "converts", "group": "Life Circumstances", "label": "Converts",
     "desc": "Saints who came to the faith from outside it.",
     "match": [{"church": ["Convert"]}]},
    {"slug": "married-saints", "group": "Life Circumstances", "label": "Married Saints",
     "desc": "Saints who lived holiness within marriage.",
     "match": [{"family": ["Married"]}]},
    {"slug": "mothers", "group": "Life Circumstances", "label": "Mothers",
     "desc": "Holy women who raised children in the faith.",
     "match": [{"gender": ["Female"], "family": ["Parent"]}]},
    {"slug": "fathers", "group": "Life Circumstances", "label": "Fathers",
     "desc": "Holy men who raised children in the faith.",
     "match": [{"gender": ["Male"], "family": ["Parent"]}]},
    {"slug": "widows", "group": "Life Circumstances", "label": "Widows",
     "desc": "Holy women who served God in widowhood.",
     "match": [{"gender": ["Female"], "family": ["Widowed"]}]},
    {"slug": "children", "group": "Life Circumstances", "label": "Children",
     "desc": "Child saints and young martyrs.",
     "match": [{"rank": ["Child-Saint"]}, {"family": ["Child"]}]},
    {"slug": "youth", "group": "Life Circumstances", "label": "Youth",
     "desc": "Saints who came to holiness in their youth.",
     "match": [{"family": ["Teen"]}]},
    {"slug": "elderly-saints", "group": "Life Circumstances", "label": "Elderly Saints",
     "desc": "Saints honored in their old age.",
     "match": [{"family": ["Grandparent"]}]},
    {"slug": "missionaries", "group": "Life Circumstances", "label": "Missionaries",
     "desc": "Saints who carried the Gospel to new peoples.",
     "match": [{"rank": ["Missionary", "Equal-to-the-Apostles", "Enlightener"]},
               {"intercession": ["Missionary Work"]}]},
    {"slug": "royal-saints", "group": "Life Circumstances", "label": "Royal Saints",
     "desc": "Kings, queens, princes, and rulers who served God.",
     "match": [{"rank": ["Right-believing (Ruler)"]}, {"vocation": ["Ruler"]}]},
    {"slug": "former-slaves", "group": "Life Circumstances", "label": "Former Slaves",
     "desc": "Saints who lived in servitude or slavery.",
     "match": [{"vocation": ["Servant / Slave"]}, {"experience": ["Slavery"]}]},
    {"slug": "former-criminals", "group": "Life Circumstances", "label": "Former Criminals",
     "desc": "Saints who turned from grave sin to holiness.",
     "match": [{"experience": ["Repentance from grave sin"]}]},
    {"slug": "orphans", "group": "Life Circumstances", "label": "Orphans",
     "desc": "Saints who lost their parents young.", "match": []},
    {"slug": "former-pagans", "group": "Life Circumstances", "label": "Former Pagans",
     "desc": "Saints raised in paganism before their conversion.", "match": []},
    {"slug": "immigrants", "group": "Life Circumstances", "label": "Immigrants",
     "desc": "Saints who settled far from their homeland.", "match": []},
    {"slug": "refugees", "group": "Life Circumstances", "label": "Refugees",
     "desc": "Saints who fled persecution or danger.", "match": []},
    {"slug": "pilgrims", "group": "Life Circumstances", "label": "Pilgrims",
     "desc": "Saints known for sacred pilgrimage.", "match": []},
    {"slug": "bishops", "group": "Vocations", "label": "Bishops",
     "desc": "Hierarchs and shepherds of the Church.",
     "match": [{"church": ["Clergy - Bishop"]}, {"rank": ["Hierarch"]}]},
    {"slug": "priests", "group": "Vocations", "label": "Priests",
     "desc": "Saints who served as priests.",
     "match": [{"church": ["Clergy - Priest"]}]},
    {"slug": "deacons", "group": "Vocations", "label": "Deacons",
     "desc": "Saints who served as deacons.",
     "match": [{"church": ["Clergy - Deacon"]}]},
    {"slug": "monastics", "group": "Vocations", "label": "Monastics",
     "desc": "Monks and nuns of the Church.",
     "match": [{"church": ["Monastic"]}, {"rank": ["Venerable (Monastic)"]}]},
    {"slug": "hermits", "group": "Vocations", "label": "Hermits",
     "desc": "Saints who withdrew into solitude.",
     "match": [{"rank": ["Hermit"]}]},
    {"slug": "physicians", "group": "Vocations", "label": "Physicians",
     "desc": "Saints who healed the sick by their craft.",
     "match": [{"vocation": ["Physician", "Nurse"]}]},
    {"slug": "teachers", "group": "Vocations", "label": "Teachers",
     "desc": "Saints who taught and catechized.",
     "match": [{"vocation": ["Teacher"]}]},
    {"slug": "writers", "group": "Vocations", "label": "Writers",
     "desc": "Saints who wrote and translated.",
     "match": [{"vocation": ["Writer", "Translator"]}]},
    {"slug": "iconographers", "group": "Vocations", "label": "Iconographers",
     "desc": "Saints who painted holy icons.",
     "match": [{"vocation": ["Iconographer"]}]},
    {"slug": "musicians", "group": "Vocations", "label": "Musicians",
     "desc": "Hymnographers and singers of the Church.",
     "match": [{"vocation": ["Musician", "Hymnographer"]}]},
    {"slug": "judges", "group": "Vocations", "label": "Judges",
     "desc": "Saints who served in judgment and law.",
     "match": [{"vocation": ["Judge"]}]},
    {"slug": "craftsmen", "group": "Vocations", "label": "Craftsmen",
     "desc": "Saints who worked with their hands.",
     "match": [{"vocation": ["Craftsman", "Architect"]}]},
    {"slug": "farmers", "group": "Vocations", "label": "Farmers",
     "desc": "Saints who worked the land and tended flocks.",
     "match": [{"vocation": ["Farmer", "Shepherd"]}]},
    {"slug": "sailors", "group": "Vocations", "label": "Sailors",
     "desc": "Saints of the sea.",
     "match": [{"vocation": ["Sailor"]}]},
    {"slug": "soldiers", "group": "Vocations", "label": "Soldiers",
     "desc": "Saints who served in arms.",
     "match": [{"vocation": ["Soldier", "Officer / General"]}]},
    {"slug": "theologians", "group": "Vocations", "label": "Theologians",
     "desc": "Saints renowned for theological learning.",
     "match": [{"vocation": ["Scholar"]}]},
    {"slug": "abbots-abbesses", "group": "Vocations", "label": "Abbots & Abbesses",
     "desc": "Leaders of monastic communities.", "match": []},
    {"slug": "humility", "group": "Virtues", "label": "Humility",
     "desc": "Saints renowned for humility.", "match": [{"virtue": ["Humility"]}]},
    {"slug": "charity", "group": "Virtues", "label": "Charity",
     "desc": "Saints renowned for almsgiving and love.", "match": [{"virtue": ["Charity"]}]},
    {"slug": "courage", "group": "Virtues", "label": "Courage",
     "desc": "Saints renowned for courage.", "match": [{"virtue": ["Courage"]}]},
    {"slug": "patience", "group": "Virtues", "label": "Patience",
     "desc": "Saints renowned for patience.", "match": [{"virtue": ["Patience"]}]},
    {"slug": "obedience", "group": "Virtues", "label": "Obedience",
     "desc": "Saints renowned for obedience.", "match": [{"virtue": ["Obedience"]}]},
    {"slug": "wisdom", "group": "Virtues", "label": "Wisdom",
     "desc": "Saints renowned for wisdom.", "match": [{"virtue": ["Wisdom"]}]},
    {"slug": "repentance", "group": "Virtues", "label": "Repentance",
     "desc": "Saints whose lives witness to repentance.",
     "match": [{"virtue": ["Repentance"]}, {"experience": ["Repentance from grave sin"]}]},
    {"slug": "hospitality", "group": "Virtues", "label": "Hospitality",
     "desc": "Saints renowned for hospitality.", "match": [{"virtue": ["Hospitality"]}]},
    {"slug": "perseverance", "group": "Virtues", "label": "Perseverance",
     "desc": "Saints renowned for perseverance.", "match": [{"virtue": ["Perseverance"]}]},
    {"slug": "faithfulness", "group": "Virtues", "label": "Faithfulness",
     "desc": "Saints renowned for steadfast faith.", "match": [{"virtue": ["Faith"]}]},
    {"slug": "forgiveness", "group": "Virtues", "label": "Forgiveness",
     "desc": "Saints renowned for forgiveness.", "match": [{"virtue": ["Forgiveness"]}]},
    {"slug": "asceticism", "group": "Virtues", "label": "Asceticism",
     "desc": "Saints of rigorous ascetic struggle.",
     "match": [{"rank": ["Ascetic", "Stylite"]}, {"virtue": ["Self-Control"]}]},
    {"slug": "love-of-enemies", "group": "Virtues", "label": "Love of Enemies",
     "desc": "Saints who loved and forgave their persecutors.", "match": []},
    {"slug": "persecution", "group": "Struggles & Trials", "label": "Persecution",
     "desc": "Saints who endured persecution.", "match": [{"experience": ["Persecution"]}]},
    {"slug": "imprisonment", "group": "Struggles & Trials", "label": "Imprisonment",
     "desc": "Saints imprisoned for the faith.",
     "match": [{"experience": ["Imprisonment", "Captivity"]}]},
    {"slug": "exile", "group": "Struggles & Trials", "label": "Exile",
     "desc": "Saints sent into exile.", "match": [{"experience": ["Exile"]}]},
    {"slug": "poverty", "group": "Struggles & Trials", "label": "Poverty",
     "desc": "Saints who embraced or endured poverty.", "match": [{"experience": ["Poverty"]}]},
    {"slug": "illness", "group": "Struggles & Trials", "label": "Illness",
     "desc": "Saints who bore illness and pain.",
     "match": [{"experience": ["Illness", "Chronic Pain"]}]},
    {"slug": "physical-disability", "group": "Struggles & Trials", "label": "Physical Disability",
     "desc": "Saints who lived with disability or blindness.",
     "match": [{"experience": ["Disability", "Blindness"]}]},
    {"slug": "grief", "group": "Struggles & Trials", "label": "Grief",
     "desc": "Saints who bore bereavement and loss.",
     "match": [{"experience": ["Grief / Bereavement", "Loss of a Child"]}]},
    {"slug": "temptation", "group": "Struggles & Trials", "label": "Temptation",
     "desc": "Saints who overcame fierce temptation.", "match": [{"experience": ["Temptation"]}]},
    {"slug": "addiction-recovery", "group": "Struggles & Trials", "label": "Addiction Recovery",
     "desc": "Saints who overcame self-destructive habits.",
     "match": [{"experience": ["Addiction / Self-destructive habits"]},
               {"intercession": ["Addiction Recovery"]}]},
    {"slug": "doubt", "group": "Struggles & Trials", "label": "Doubt",
     "desc": "Saints who passed through doubt to faith.", "match": [{"experience": ["Doubt"]}]},
    {"slug": "martyrdom", "group": "Struggles & Trials", "label": "Martyrdom",
     "desc": "Saints who died for Christ.",
     "match": [{"rank": ["Martyr", "Great Martyr", "Hieromartyr", "New Martyr",
                         "Venerable-Martyr", "Passion-Bearer"]}]},
    {"slug": "torture", "group": "Struggles & Trials", "label": "Torture",
     "desc": "Saints who endured torture for the faith.", "match": [{"experience": ["Torture"]}]},
    {"slug": "family-conflict", "group": "Struggles & Trials", "label": "Family Conflict",
     "desc": "Saints who bore strife within the family.",
     "match": [{"experience": ["Difficult Marriage"]}]},
    {"slug": "spiritual-warfare", "group": "Struggles & Trials", "label": "Spiritual Warfare",
     "desc": "Saints who battled the passions and demons.", "match": []},
    {"slug": "apostolic-age", "group": "Historical Themes", "label": "Apostolic Age",
     "desc": "The apostles and the earliest Church.",
     "match": [{"era": ["Apostolic Age"]}, {"rank": ["Apostle", "Equal-to-the-Apostles"]}]},
    {"slug": "desert-fathers", "group": "Historical Themes", "label": "Desert Fathers",
     "desc": "The monastic fathers of the Egyptian desert.",
     "match": [{"gender": ["Male"], "origin": ["Egypt"],
                "rank": ["Venerable (Monastic)", "Ascetic", "Hermit"]}]},
    {"slug": "desert-mothers", "group": "Historical Themes", "label": "Desert Mothers",
     "desc": "The monastic mothers of the Egyptian desert.",
     "match": [{"gender": ["Female"], "origin": ["Egypt"],
                "rank": ["Venerable (Monastic)", "Ascetic", "Hermit"]}]},
    {"slug": "early-martyrs", "group": "Historical Themes", "label": "Early Martyrs",
     "desc": "Martyrs of the first Christian centuries.",
     "match": [{"rank": ["Martyr", "Great Martyr", "Hieromartyr"],
                "era": ["Apostolic Age", "Pre-Nicene"]}]},
    {"slug": "byzantine-saints", "group": "Historical Themes", "label": "Byzantine Saints",
     "desc": "Saints of the Byzantine era.", "match": [{"era": ["Byzantine"]}]},
    {"slug": "slavic-saints", "group": "Historical Themes", "label": "Slavic Saints",
     "desc": "Saints of the Slavic lands.",
     "match": [{"origin": ["Rus' / Russia", "Ukraine", "Serbia", "Bulgaria"]},
               {"tradition": ["Russian", "Serbian", "Bulgarian"]}]},
    {"slug": "celtic-saints", "group": "Historical Themes", "label": "Celtic Saints",
     "desc": "Saints of the Celtic British Isles.",
     "match": [{"origin": ["Ireland", "Scotland", "Wales", "British Isles"]}]},
    {"slug": "new-martyrs", "group": "Historical Themes", "label": "New Martyrs",
     "desc": "Martyrs of the modern era.", "match": [{"rank": ["New Martyr"]}]},
    {"slug": "saints-of-america", "group": "Historical Themes", "label": "Saints of America",
     "desc": "Saints of North America.",
     "match": [{"origin": ["North America", "Alaska"]}, {"tradition": ["North American"]}]},
    {"slug": "saints-of-alaska", "group": "Historical Themes", "label": "Saints of Alaska",
     "desc": "Saints who labored in Alaska.", "match": [{"origin": ["Alaska"]}]},
    {"slug": "saints-under-communism", "group": "Historical Themes", "label": "Saints Under Communism",
     "desc": "Saints who suffered under communist regimes.",
     "match": [{"era": ["Modern"], "rank": ["New Martyr"],
                "origin": ["Rus' / Russia", "Ukraine", "Romania", "Serbia", "Bulgaria", "Baltics", "Georgia"]},
               {"era": ["Modern"], "experience": ["Persecution"],
                "origin": ["Rus' / Russia", "Ukraine", "Romania", "Serbia", "Bulgaria", "Baltics", "Georgia"]}]},
    {"slug": "ottoman-era-saints", "group": "Historical Themes", "label": "Ottoman-Era Saints",
     "desc": "Saints under Ottoman rule.",
     "match": [{"era": ["Post-Byzantine"],
                "origin": ["Greece", "Constantinople", "Asia Minor", "Serbia", "Bulgaria", "Romania", "Thrace"]},
               {"era": ["Post-Byzantine"], "rank": ["New Martyr"]}]},
    {"slug": "confessors", "group": "Historical Themes", "label": "Confessors",
     "desc": "Saints who confessed the faith under pressure.", "match": [{"rank": ["Confessor"]}]},
    {"slug": "hierarchs", "group": "Historical Themes", "label": "Hierarchs",
     "desc": "The great hierarchs of the Church.", "match": [{"rank": ["Hierarch"]}]},
    {"slug": "defenders-of-orthodoxy", "group": "Historical Themes", "label": "Defenders of Orthodoxy",
     "desc": "Saints who defended the Orthodox faith.", "match": []},
    {"slug": "icon-defenders", "group": "Historical Themes", "label": "Icon Defenders",
     "desc": "Saints who defended the holy icons.", "match": []},
    {"slug": "anti-arian-saints", "group": "Historical Themes", "label": "Anti-Arian Saints",
     "desc": "Saints who opposed the Arian heresy.", "match": []},
    {"slug": "ecumenical-councils", "group": "Historical Themes", "label": "Ecumenical Councils",
     "desc": "Fathers of the Ecumenical Councils.", "match": []},
    {"slug": "apologists", "group": "Historical Themes", "label": "Apologists",
     "desc": "Saints who defended the faith in writing.", "match": []},
    {"slug": "church-fathers", "group": "Historical Themes", "label": "Church Fathers",
     "desc": "The Fathers whose teaching shaped the Church.", "match": []},
    {"slug": "holy-families", "group": "Family & Relationships", "label": "Holy Families",
     "desc": "Families that gave many saints to the Church.", "match": []},
    {"slug": "saintly-siblings", "group": "Family & Relationships", "label": "Saintly Siblings",
     "desc": "Brothers and sisters who are both saints.", "match": []},
    {"slug": "married-couples", "group": "Family & Relationships", "label": "Married Couples",
     "desc": "Husband-and-wife saints.", "match": []},
    {"slug": "spiritual-fathers", "group": "Family & Relationships", "label": "Spiritual Fathers",
     "desc": "Elders who guided others in the faith.", "match": []},
    {"slug": "spiritual-mothers", "group": "Family & Relationships", "label": "Spiritual Mothers",
     "desc": "Eldresses who guided others in the faith.", "match": []},
    {"slug": "godparents", "group": "Family & Relationships", "label": "Godparents",
     "desc": "Saints honored as godparents.", "match": []},
    {"slug": "mentors-disciples", "group": "Family & Relationships", "label": "Mentors & Disciples",
     "desc": "Saints bound as teacher and disciple.", "match": []},
    {"slug": "wonderworkers", "group": "Miracles & Wonders", "label": "Wonderworkers",
     "desc": "Saints through whom God worked wonders.", "match": [{"rank": ["Wonderworker"]}]},
    {"slug": "healers", "group": "Miracles & Wonders", "label": "Healers",
     "desc": "Saints through whom God healed body and soul.",
     "match": [{"rank": ["Unmercenary"]}, {"vocation": ["Physician"]},
               {"intercession": ["Healing"]}]},
    {"slug": "prophecy", "group": "Miracles & Wonders", "label": "Prophecy",
     "desc": "Prophets and saints of foresight.", "match": [{"rank": ["Prophet", "Forerunner"]}]},
    {"slug": "miracle-working-relics", "group": "Miracles & Wonders", "label": "Miracle-Working Relics",
     "desc": "Saints whose relics work wonders.", "match": []},
    {"slug": "miracle-working-icons", "group": "Miracles & Wonders", "label": "Miracle-Working Icons",
     "desc": "Saints associated with wonderworking icons.", "match": []},
    {"slug": "visions", "group": "Miracles & Wonders", "label": "Visions",
     "desc": "Saints granted holy visions.", "match": []},
    {"slug": "apparitions", "group": "Miracles & Wonders", "label": "Apparitions",
     "desc": "Saints who appeared after their repose.", "match": []},
    {"slug": "holy-land", "group": "Geographic Themes", "label": "Holy Land",
     "desc": "Saints of Palestine and Sinai.",
     "match": [{"origin": ["Palestine / Holy Land", "Sinai"]}]},
    {"slug": "egypt", "group": "Geographic Themes", "label": "Egypt",
     "desc": "Saints of Egypt.", "match": [{"origin": ["Egypt"]}]},
    {"slug": "greece", "group": "Geographic Themes", "label": "Greece",
     "desc": "Saints of Greece and Constantinople.",
     "match": [{"origin": ["Greece", "Constantinople"]}]},
    {"slug": "asia-minor", "group": "Geographic Themes", "label": "Asia Minor",
     "desc": "Saints of Asia Minor.",
     "match": [{"origin": ["Asia Minor", "Pontus", "Thrace"]}]},
    {"slug": "balkans", "group": "Geographic Themes", "label": "Balkans",
     "desc": "Saints of the Balkans.",
     "match": [{"origin": ["Serbia", "Bulgaria", "Romania", "Thrace"]}]},
    {"slug": "russia", "group": "Geographic Themes", "label": "Russia",
     "desc": "Saints of Russia and Ukraine.",
     "match": [{"origin": ["Rus' / Russia", "Ukraine"]}]},
    {"slug": "georgia", "group": "Geographic Themes", "label": "Georgia",
     "desc": "Saints of Georgia.", "match": [{"origin": ["Georgia"]}]},
    {"slug": "romania", "group": "Geographic Themes", "label": "Romania",
     "desc": "Saints of Romania.", "match": [{"origin": ["Romania"]}]},
    {"slug": "serbia", "group": "Geographic Themes", "label": "Serbia",
     "desc": "Saints of Serbia.", "match": [{"origin": ["Serbia"]}]},
    {"slug": "antioch", "group": "Geographic Themes", "label": "Antioch",
     "desc": "Saints of Antioch and Syria.",
     "match": [{"origin": ["Syria"]}, {"tradition": ["Antiochian"]}]},
    {"slug": "western-europe", "group": "Geographic Themes", "label": "Western Europe",
     "desc": "Pre-schism saints of Western Europe.",
     "match": [{"origin": ["Italy / Rome", "Gaul / France", "Germany", "Spain"]}]},
    {"slug": "british-isles", "group": "Geographic Themes", "label": "British Isles",
     "desc": "Saints of the British Isles.",
     "match": [{"origin": ["British Isles", "Ireland", "Scotland", "Wales", "England"]}]},
    {"slug": "alexandria", "group": "Geographic Themes", "label": "Alexandria",
     "desc": "Saints of Alexandria.", "match": []},
]

THEME_SLUGS = {t["slug"] for t in THEMES}
THEME_LABELS = {t["slug"]: t["label"] for t in THEMES}

# Query fragments (lowercased) -> theme slug, for the finder's "Browse the
# <label> theme" banner. Emitted into public/themes.json so the frontend never
# duplicates theme knowledge. ORDER MATTERS: first matching fragment wins.
ALIASES = [
    {"phrase": "defended icons", "slug": "icon-defenders"},
    {"phrase": "icon defender", "slug": "icon-defenders"},
    {"phrase": "in america", "slug": "saints-of-america"},
    {"phrase": "in alaska", "slug": "saints-of-alaska"},
    {"phrase": "soldier", "slug": "soldiers"},
    {"phrase": "mother", "slug": "mothers"},
    {"phrase": "father", "slug": "fathers"},
    {"phrase": "convert", "slug": "converts"},
    {"phrase": "martyr", "slug": "martyrdom"},
    {"phrase": "exile", "slug": "exile"},
    {"phrase": "persecut", "slug": "persecution"},
    {"phrase": "physician", "slug": "physicians"},
    {"phrase": "doctor", "slug": "physicians"},
    {"phrase": "monk", "slug": "monastics"},
    {"phrase": "nun", "slug": "monastics"},
    {"phrase": "monastic", "slug": "monastics"},
    {"phrase": "bishop", "slug": "bishops"},
    {"phrase": "missionary", "slug": "missionaries"},
    {"phrase": "missionaries", "slug": "missionaries"},
    {"phrase": "wonderworker", "slug": "wonderworkers"},
    {"phrase": "healer", "slug": "healers"},
]

_SEP = "; "


def _split(s):
    return [p.strip() for p in (s or "").split(_SEP) if p.strip()]


def _rule_matches(rule, rec):
    for field, allowed in rule.items():
        vals = rec.get(field, [])
        if isinstance(vals, str):
            vals = [vals] if vals else []
        if not (set(vals) & set(allowed)):
            return False
    return True


def compute_themes(rec, override=""):
    """Return ordered, de-duplicated theme slugs for a record dict."""
    slugs = []
    for t in THEMES:
        if any(_rule_matches(rule, rec) for rule in t["match"]):
            slugs.append(t["slug"])
    for s in _split(override):
        if s not in slugs:
            slugs.append(s)
    return slugs


def theme_catalog(records):
    """[{slug, group, label, desc, count}] in THEMES order; count over records."""
    counts = {}
    for r in records:
        for s in r.get("themes", []):
            counts[s] = counts.get(s, 0) + 1
    return [{"slug": t["slug"], "group": t["group"], "label": t["label"],
             "desc": t["desc"], "count": counts.get(t["slug"], 0)} for t in THEMES]
